default_args:
  prod:
    owner: 'Docente'
    start_date: '2024-04-30'
    retries: 1
  staging:    
    owner: 'Inspector'
    start_date: '2024-04-22'
    retries: 1

  dev:
    owner: 'Desarrollador'
    start_date: '2024-04-22'
    retries: 5


dag_caracteristicas:
  prod:
    schedule_interval: '* * * * *'
    start_date: '2024-04-30'
    max_active_runs: 1
    catchup: True
    max_active_tasks: 3   
    description: 'Un DAG de ejemplo que combina taskgroup, xcom, sensor, triggerrules y separación de forma modular - PRODUCCION'

  staging:    
    schedule_interval: '@daily'
    start_date: '2024-01-01'
    max_active_runs: 1
    catchup: False
    max_active_tasks: 1
    description: 'Un DAG de ejemplo que combina taskgroup, xcom, sensor, triggerrules y separación de forma modular - STAGING'    
  dev:
    schedule_interval: '@weekly'
    start_date: '2024-04-22'
    max_active_runs: 1
    catchup: False
    max_active_tasks: 1
    description: 'Un DAG de ejemplo que combina taskgroup, xcom, sensor, triggerrules y separación de forma modular - DESARRROLLO'
        